### ISSUE TITLE
closed issue와 pull request도 count하나요?

### ISSUE THREAD

**Issue by hckimfe** [yunkon-kim/github-influence-factors-counter#11]
본 counter는 close된 issue의 갯수와 close된 pull request도 count하나요?

**Comment by yunkon-kim** [comment]
@hckimfe 
안녕하세요.

한동안 모니터링 하고 있지 않아 답변이 늦었습니다. 양해 바랍니다 🙏 

제가 count해봤던 항목은 아래와 같습니다. (코드 정리는 안되어 있습니다ㅠㅠ) 
- Contributors
- Stars
- Forks
- Watches
- Commits (특정 기간)

말씀하신 내용도 [GitHub REST API](https://docs.github.com/en/rest)를 활용하면 가능할 것 같네요 😄

**Comment by yunkon-kim** [comment]
Available since https://github.com/yunkon-kim/github-influence-factors-counter/commit/f650d9dab9ebc44e79dcec814beaf0338f6ccdcb
